/**
 * Type qui reporesentent les identifiants des différents types de fichiers Minecraft.
 */
export type MinecraftFileId =
    "behavior_pack/aim_assist/categories/categories.json" |
    "behavior_pack/aim_assist/presets/<all>.json" |
    "behavior_pack/animation_controllers/<all>.json" |
    "behavior_pack/animations/<all>.json" |
    "behavior_pack/biomes/<all>.json" |
    "behavior_pack/blocks/<all>.json" |
    "behavior_pack/cameras/presets/<all>.json" |
    "behavior_pack/dialogue/<all>.json" |
    "behavior_pack/dimensions/<all>.json" |
    "behavior_pack/entities/<all>.json" |
    "behavior_pack/feature_rules/<all>.json" |
    "behavior_pack/features/<all>.json" |
    "behavior_pack/functions/<all>.mcfunction" |
    "behavior_pack/functions/tick.json" |
    "behavior_pack/item_catalog/crafting_item_catalog.json" |
    "behavior_pack/items/<all>.json" |
    "behavior_pack/loot_tables/<all>.json" |
    "behavior_pack/recipes/<all>.json" |
    "behavior_pack/spawn_rules/<all>.json" |
    "behavior_pack/structures/<all>.{mcstructure,nbt}" |
    "behavior_pack/texts/<all>.lang" |
    "behavior_pack/texts/languages.json" |
    "behavior_pack/trading/<all>.json" |
    "behavior_pack/worldgen/processors/<all>.json" |
    "behavior_pack/worldgen/structure_sets/<all>.json" |
    "behavior_pack/worldgen/structures/<all>.json" |
    "behavior_pack/worldgen/template_pools/<all>.json" |
    "behavior_pack/contents.json" |
    "behavior_pack/manifest.json" |
    "behavior_pack/pack_icon.png" |
    "resource_pack/animation_controllers/<all>.json" |
    "resource_pack/animations/<all>.json" |
    "resource_pack/atmospherics/<all>.json" |
    "resource_pack/attachables/<all>.json" |
    "resource_pack/biomes/<all>.json" |
    "resource_pack/block_culling/<all>.json" |
    "resource_pack/color_grading/<all>.json" |
    "resource_pack/credits/credits.json" |
    "resource_pack/entity/<all>.json" |
    "resource_pack/fogs/<all>.json" |
    "resource_pack/font/emoticons.json" |
    "resource_pack/font/font_metadata.json" |
    "resource_pack/font/<all>.png" |
    "resource_pack/font/<all>.ttf" |
    "resource_pack/items/<all>.json" |
    "resource_pack/lighting/<all>.json" |
    "resource_pack/materials/<all>.material" |
    "resource_pack/models/<all>.json" |
    "resource_pack/particles/<all>.json" |
    "resource_pack/pbr/global.json" |
    "resource_pack/render_controllers/<all>.json" |
    "resource_pack/shadows/global.json" |
    "resource_pack/sounds/*.{wav,mp3,ogg,fsb}" |
    "resource_pack/sounds/music_definitions.json" |
    "resource_pack/sounds/sound_definitions.json" |
    "resource_pack/texts/language_names.json" |
    "resource_pack/texts/languages.json" |
    "resource_pack/textures/<all>.texture_set.json" |
    "resource_pack/textures/flipbook_textures.json" |
    "resource_pack/textures/item_texture.json" |
    "resource_pack/textures/terrain_texture.json" |
    "resource_pack/textures/textures_list.json" |
    "resource_pack/textures/*.{tga,png,jpg,jpeg}" |
    "resource_pack/ui/_global_variables.json" |
    "resource_pack/ui/_ui_defs.json" |
    "resource_pack/ui/<all>.json" |
    "resource_pack/water/<all>.json" |
    "resource_pack/biomes_client.json" |
    "resource_pack/blocks.json" |
    "resource_pack/contents.json" |
    "resource_pack/loading_messages.json" |
    "resource_pack/manifest.json" |
    "resource_pack/sounds.json" |
    "resource_pack/splashes.json"