export const schemaEnums = {
    menu_categories: ["construction", "nature", "equipment", "items", "none"],
    tint_methods: ["none", "default_foliage", "birch_foliage", "evergreen_foliage", "dry_foliage", "grass", "water"],
    entity_damage_causes: ["all", "anvil", "block_explosion", "campfire", "charging", "contact", "drowning", "entity_attack", "entity_explosion", "fall", "falling_block", "fire", "fire_tick", "fireworks", "fly_into_wall", "freezing", "lava", "lightning", "mace_smash", "magic", "magma", "none", "override", "piston", "projectile", "ram_attack", "self_destruct", "sonic_boom", "soul_campfire", "stalactite", "stalagmite", "starve", "suffocation", "temperature", "thorns", "void", "wither"]
};

export const dynamicExamplesSourceKeys = {
    aim_assist_category_ids: "aim_assist_category_ids",
    aim_assist_preset_ids: "aim_assist_preset_ids",
    atmosphere_settings_ids: "atmosphere_settings_ids",
    behavior_animation_ids: "behavior_animation_ids",
    behavior_animation_controller_ids: "behavior_animation_controller_ids",
    biome_ids: "biome_ids",
    biome_tags: "biome_tags",
    block_culling_rules_ids: "block_culling_rules_ids",
    block_ids: "block_ids",
    block_texture_references: "block_texture_references",
    cooldown_category_ids: "cooldown_category_ids",
    color_grading_settings_ids: "color_grading_settings_ids",
    culling_layer_ids: "culling_layer_ids",
    crafting_recipe_tags: "crafting_recipe_tags",

    data_driven_aim_assist_category_ids: "data_driven_aim_assist_category_ids",
    data_driven_aim_assist_preset_ids: "data_driven_aim_assist_preset_ids",
    data_driven_atmosphere_settings_ids: "data_driven_atmosphere_settings_ids",
    data_driven_attachable_ids: "data_driven_attachable_ids",
    data_driven_biome_ids: "data_driven_biome_ids",
    data_driven_camera_preset_ids: "data_driven_camera_preset_ids",
    data_driven_color_grading_settings_ids: "data_driven_color_grading_settings_ids",
    data_driven_dimension_ids: "data_driven_dimension_ids",
    data_driven_feature_rules_ids: "data_driven_feature_rules_ids",
    data_driven_fog_ids: "data_driven_fog_ids",
    data_driven_item_ids: "data_driven_item_ids",
    data_driven_jigsaw_structure_ids: "data_driven_jigsaw_structure_ids",
    data_driven_lighting_settings_ids: "data_driven_lighting_settings_ids",
    data_driven_model_ids: "data_driven_model_ids",
    data_driven_particle_effect_ids: "data_driven_particle_effect_ids",
    data_driven_processor_ids: "data_driven_processor_ids",
    data_driven_render_controller_ids: "data_driven_render_controller_ids",
    data_driven_resource_animation_controller_ids: "data_driven_resource_animation_controller_ids",
    data_driven_resource_animation_ids: "data_driven_resource_animation_ids",
    data_driven_spawn_rules_ids: "data_driven_spawn_rules_ids",
    data_driven_structure_set_ids: "data_driven_structure_set_ids",
    data_driven_template_pool_ids: "data_driven_template_pool_ids",
    data_driven_water_settings_ids: "data_driven_water_settings_ids",

    effect_ids: "effect_ids",
    entity_ids: "entity_ids",
    feature_ids: "feature_ids",
    fog_ids: "fog_ids",
    full_block_model_id: "full_block_model_id",
    inheritable_camera_preset_ids: "inheritable_camera_preset_ids",
    item_group_ids: "item_group_ids",
    item_ids: "item_ids",
    item_texture_references: "item_texture_references",
    lighting_settings_ids: "lighting_settings_ids",
    loot_table_file_paths: "loot_table_file_paths",
    model_ids: "model_ids",
    particle_effect_ids: "particle_effect_ids",
    render_controller_ids: "render_controller_ids",
    resource_animation_controller_ids: "resource_animation_controller_ids",
    resource_animation_ids: "resource_animation_ids",
    texture_file_paths: "texture_file_paths",

    vanilla_biome_ids: "vanilla_biome_ids",
    vanilla_biome_ids_without_namespace: "vanilla_biome_ids_without_namespace",
    vanilla_block_ids_without_namespace: "vanilla_block_ids_without_namespace",
    vanilla_camera_preset_ids: "vanilla_camera_preset_ids",
    vanilla_dimension_ids: "vanilla_dimension_ids",
    vanilla_entity_ids_without_namespace: "vanilla_entity_ids_without_namespace",
    vanilla_item_group_ids_without_namespace: "vanilla_item_group_ids_without_namespace",
    water_settings_ids: "water_settings_ids",

    trading_file_paths: "trading_file_paths",
    vanilla_data_driven_item_ids: "vanilla_data_driven_item_ids",
    item_tags: "item_tags",
    vanilla_data_driven_entity_ids: "vanilla_data_driven_entity_ids",
    camera_preset_ids: "camera_preset_ids",
    entity_family_ids: "entity_family_ids"
};