name: Deploy Schemas (Dev)

on: 
    push: 
        branches: ["dev"] # <--- C'EST ICI QU'ON CHANGE : On cible ta branche de travail

permissions: 
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    deploy:
        environment: 
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"
            
            - name: Install Dependencies
              run: npm ci
            
            - name: Build Schemas
              run: npm run build-schemas # Lance ton script tsx
            
            - name: Setup Pages
              uses: actions/configure-pages@v5
            
            - name: Upload Artifact
              uses: actions/upload-pages-artifact@v3
              with:
                # Attention: vérifie bien que ce chemin correspond à ton dossier de sortie local
                path: './dist/minecraftSchemas'
            
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4